import localFont from "next/font/local";
import "./globals.css";
import CustomNavbar from "@/components/customNavbar";
import Footer from "@/components/footer";
import { ToastContainer } from "react-toastify";
import UserProvider from "@/context/userProvider";

// Load fonts without conditional checks
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       <UserProvider>
        <ToastContainer />
          <CustomNavbar /> {/* Ensure you are using PascalCase */}
          <div >{children}</div>
          <Footer />
       </UserProvider>
      </body>
    </html>
  );
}
